Repository oscarso2000/MyCourseIndex, pull requests merged in 2020-09, with the labels that each got.

#145 feat(deploy): CNAME mods for deploy
  deployment.yaml
Labels: Architecture / Search, Client Engagement, Priority: Urgent

#144 Added New Team Members to Abouts page and updated description
  app/__init__.py
  client/src/components/About.tsx
  client/src/images/David_Kim.jpg
  client/src/images/Elva_Gao.jpg
  client/src/images/Jessie_Lee.png
  client/src/images/John_O.jpg
  client/src/images/Julia_Ng.jpg
  client/src/images/Katie_Yang.jpg
  client/src/style/About.css
  client/src/style/CourseSelection.css
  deployment.yaml
Labels: UI / UX

#146 chore: cleaning up random large files
  PDF Documents/P01.pdf
  PDF Documents/P02.pdf
  charts.py
  client/package-lock.json
  cosineSimilarity/Cosine.py
  cosineSimilarity/alice29.txt
  cosineSimilarity/utils.py
  preprocess/preprocess.ipynb
  preprocess/preprocess.py
  preprocess/preprocessutils.py
Labels: Cleanup, Priority: High

#148 [UX/UI] Issue #147 : Fix large space in list of courses CSS
  client/src/components/CourseSelection.tsx
  client/src/components/Mediacardnomodal.tsx
  client/src/components/MultipleCoursesModal/container.tsx
  client/src/config/adalConfig.ts
  client/src/style/CourseSelection.css
  piazza-api/.DS_Store
  poetry.lock
Labels: Priority: Urgent, UI / UX, bug
